package com.machinespray.osfeloader.frame;

import com.machinespray.osfeloader.Main;
import com.machinespray.osfeloader.handler.LuaHandler;
import com.machinespray.osfeloader.handler.MouseHandler;
import com.machinespray.osfeloader.handler.SaveHandler;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

public class DialogDisplaySpells extends JDialog {
	public JTree spellDisplay;
	private JPanel contentPane;
	private JButton buttonOK;
	private JButton buttonCancel;
	private JTree artifactDisplay;
	private JTabbedPane tabbedPane1;
	private ArrayList<Image> icons = new ArrayList<>();


	public DialogDisplaySpells() {
		//Show on taskbar
		super((Dialog) null, "OSFE Mod Loader");
		icons.add(new ImageIcon(getClass().getResource("/Icons/icon.png")).getImage());
		icons.add(new ImageIcon(getClass().getResource("/Icons/icon2.png")).getImage());
		setIconImages(icons);
		$$$setupUI$$$();
		setContentPane(contentPane);
		setModal(true);
		getRootPane().setDefaultButton(buttonOK);

		buttonOK.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				onOK();
			}
		});

		buttonCancel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				onCancel();
			}
		});

		// call onCancel() when cross is clicked
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				onCancel();
			}
		});

		// call onCancel() on ESCAPE
		contentPane.registerKeyboardAction(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				onCancel();
			}
		}, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
		MouseHandler mouseHandler = new MouseHandler();
		spellDisplay.addMouseListener(mouseHandler);
		artifactDisplay.addMouseListener(mouseHandler);
	}

	private void onOK() {
		try {
			SaveHandler.doOutput(Main.spellHolder);
			SaveHandler.doOutput(Main.artifactHolder);
			new LuaHandler().migrateLua();
		} catch (Exception e) {
			Main.handleError(e);
		}
		dispose();
		JOptionPane.showMessageDialog(null, "Done!");
	}

	private void onCancel() {
		// add your code here if necessary
		dispose();
		System.exit(0);
	}

	private void createUIComponents() {
		spellDisplay = Main.spellHolder.getTree();
		artifactDisplay = Main.artifactHolder.getTree();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
		contentPane.setDoubleBuffered(true);
		contentPane.setName("SpellList");
		contentPane.setPreferredSize(new Dimension(250, 250));
		tabbedPane1 = new JTabbedPane();
		contentPane.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setAutoscrolls(false);
		tabbedPane1.addTab("Spells", scrollPane1);
		spellDisplay.setName("spellDisplay");
		spellDisplay.setRootVisible(false);
		spellDisplay.putClientProperty("JTree.lineStyle", "");
		scrollPane1.setViewportView(spellDisplay);
		final JScrollPane scrollPane2 = new JScrollPane();
		tabbedPane1.addTab("Artifacts", scrollPane2);
		artifactDisplay.setRootVisible(false);
		scrollPane2.setViewportView(artifactDisplay);
		buttonOK = new JButton();
		buttonOK.setText("OK");
		contentPane.add(buttonOK, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		buttonCancel = new JButton();
		buttonCancel.setText("Cancel");
		contentPane.add(buttonCancel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
